import "../styles/globals.css";

import type { Metadata } from "next";

import GradientBackground from "@/components/background";
import Providers from "@/components/app-providers";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`dark antialiased selection:bg-cyan-300 selection:text-cyan-900 text-foreground bg-[#0D121F]`}
            >
                <GradientBackground />
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
